apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: student
  labels:
    app: studentsurveyapi
  name: studentsurveyapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: studentsurveyapi
  template:
    metadata:
      labels:
        app: studentsurveyapi
    spec:
      containers:
      - image: cparupal/studentsurveyapi:1
        imagePullPolicy: Always
        name: studentsurvey
        ports:
        - containerPort: 8080
          name: ssapi-port
          protocol: TCP
