apiVersion: v1	
kind: Service	
metadata:	
  namespace: student
  name: studentsurveyapi	
spec:	
  ports:	
  - name: http
    port: 8080	
    targetPort: 8080
  type: NodePort
  selector:	
    app: studentsurveyapi
